docs(experimenter): July's month newsletter
mozilla/experimenter-docs pull request #294
Opened 2022-08-16 18:30 UTC by yashika-khurana

## Description
- July's month newsletter

2022-08-16 18:39 UTC, jaredlockhart requested changes
Couple small changes but looks great thanks @yashika-khurana !

2022-08-16 18:39 UTC, jaredlockhart commented on docs/whats-news/2022/2022-07.md
> +  Firefox 104 is removing support for Feature.enabled, so recipes targeting it should not use the Feature.enabled flag. As a result, Experiments for Firefox Desktop 104.And above requires you to have
```
Firefox Desktop 104 is removing support for the feature enabled toggle, so experiments Firefox Desktop 104 and above will require feature enabled to be on for every branch.
```

2022-08-16 18:39 UTC, jaredlockhart commented on docs/whats-news/2022/2022-07.md
> +  The feature enabled flag was never implemented on mobile, so allowing it in the UI creates the false impression that it has some meaning for mobile experiments. So we have removed the feature-enabl
```
The feature enabled flag has been disabled entirely for mobile experiments.  Every branch of a mobile experiment must specify a feature value, which may explicitly be an empty object "{}".
```

2022-08-16 18:39 UTC, jaredlockhart commented on docs/whats-news/2022/2022-07.md
> +Normandy will continue to be supported until Nimbus can take over all of its capabilities. So in the meanwhile, we have restored the create button in legacy.
```
 Normandy will continue to be supported until Nimbus can take over for its responsibilities. So in the meanwhile, we have restored the create button in the old Experimenter interface.
```

2022-08-18 19:06 UTC, shell1 approved these changes
this looks good to me.  Thanks Yashika!   I'm approving

2022-08-18 19:11 UTC, jaredlockhart approved these changes
Thanks @yashika-khurana !

2022-08-18 19:35 UTC, merged