Fixes mozilla/experimenter#7585 docs(nimbus): Add rollouts documentation
mozilla/experimenter-docs pull request #300
Opened 2022-08-22 22:25 UTC by eliserichards

## Description (optional)

Adding basic documentation for rollouts. This uses https://mozilla-hub.atlassian.net/browse/EXP-1219 as a starting point.

todo: 
- [ ] what is a rollout/how is a rollout different from an experiment
- [x] future work **(Question:** should this link to jira?)
- [ ] formatting
- [ ] **Question:** I slotted this under Docs -> Deep Dives -> Specifications.. is there a better place to put this? 

## Issue that this pull request resolves (optional)

Closes: mozilla/experimenter#7585

## Other information (optional)

Any other information or requests important to this pull request. Remove this section if not applicable.

If you're not certain that your Markdown will render correctly, you can include this line:
I have not ran the project locally with my changes and it would be be ideal for the reviewer to check into my branch and ensure images etc. are rendering as expected.

2022-08-30 19:58 UTC, jaredlockhart requested changes
This is a good start @eliserichards but I think it's missing some of the most impoirtant information about rollouts, ie the interaction between rollouts and experiments on a given client, which include
- A client can be enrolled in both a single experiment AND rollout for a given feature
- The experiment feature value takes precedence over the rollout feature value
- Rollouts use a separate bucketing namespace from experiments so you don't need to worry about the populations colliding

There's more relevant design information in the planning doc

https://docs.google.com/document/d/1jCIWgHfVVB_u5323atF8CqZgSfQ0b88RcAMYBvQZsH8/edit?usp=sharing

that we could incorporate into this.

I like the setup of thinking about it from a 'I want to...' user story kind of perspective, but we might want to have like two sections, one talking about 'this is what it does and how it works' and one like 'I want to X here's how you do it' type thing.

Also we'll also need to update this little bit over here:

https://github.com/mozilla/experimenter-docs/blob/main/docs/getting-started/desktop-feature-api.mdx#configuration-sources

to mention that it'll use the rollout value.

It's also a bit wonky having that explanation scoped inside the desktop feature API when it applies on both desktop and mobile, maybe we wanna pull that out somewhere more generic?  Or at least replicate it into the mobile docs?  Not sure.

But thank you for getting this started 🙏

2022-08-30 19:58 UTC, jaredlockhart commented on docs/deep-dives/experimenter/rollouts.mdx
> +> ⚠️  See "Future work", live editability
Let's not even mention this until it's implemented.

2022-08-30 19:58 UTC, jaredlockhart commented on docs/deep-dives/experimenter/rollouts.mdx
> +Rollouts are single-branch experiments that differ from a traditional experiment in a number of ways.
It's not really right to say a rollout is an experiment, maybe just say a rollout differs froman experiment in a number of ways.

2022-08-30 19:58 UTC, jaredlockhart commented on docs/deep-dives/experimenter/rollouts.mdx
> +- I should to view all live experiments and rollouts for a given feature.
`I should to`?

2022-09-02 19:06 UTC, eliserichards commented
I stole those three bullet points from your review @jaredlockhart. I didn't change the desktop docs, since I'm not sure if it should be there or if we should have a section within the rollouts docs that's linked from desktop & mobile? we can chat about this later

2022-09-07 17:22 UTC, jaredlockhart approved these changes
Yep let's get it going and fill in more as time goes on.  Thanks @eliserichards ! 🎉 🎉 🎉

2022-09-07 19:52 UTC, merged