Update iOS installation instructions to get the nimbus-fml.sh file from Application Services
mozilla/experimenter-docs pull request #519
Opened 2023-10-19 13:49 UTC by jhugman

Fixes [EXP-3953](https://mozilla-hub.atlassian.net/browse/EXP-3953).

This is to facilitate `validate` being called on iOS projects, warning developers to add feature metadata to their features.

## Description (optional)

-

## Issue that this pull request resolves (optional)

This will link to and close an issue in GitHub. Replace `experimenter` with the repository where the issue lives and replace `0000` with the issue number. Remove this section if not applicable.

Closes: mozilla/experimenter#0000

## Other information (optional)

Any other information or requests important to this pull request. Remove this section if not applicable.

If you're not certain that your Markdown will render correctly, you can include this line:
I have not ran the project locally with my changes and it would be be ideal for the reviewer to check into my branch and ensure images etc. are rendering as expected.

2023-10-19 19:41 UTC, jrbenny35 requested changes
One small change

2023-10-19 19:41 UTC, jrbenny35 commented on docs/getting-started/engineers/02-ios-integration.md
> +If you need to move the `nimbus.fml.yaml` file, then you should edit this in the call in the bootstrap and in the `nimbus-fml-configuration.sh` file.
```suggestion
If you need to move the `nimbus.fml.yaml` file, then you should edit this in the call in the `bootstrap.sh` file and in the `nimbus-fml-configuration.sh` file.
```

2023-10-19 19:55 UTC, jaredlockhart approved these changes
Very nice 👍

2023-10-20 00:27 UTC, jrbenny35 approved these changes

2023-10-20 00:27 UTC, merged